

build:
	gcc -std=c18 -Werror -Wall ./src/input.c -o ./build/input -s

preprocessor:
	echo "reprocessor"

compiler:
	echo "compiler"

assembler:
	echo "assembler"

linker:
	echo "linker"

locator:
	echo "locator"

loader:
	echo "loader"

install:
	echo "install"

setup: 
	mkdir ./build ./src

execute:
	./build/input

clean:
	rm -rf ./build/*.o