

build:
	gcc -std=c18 -Wall -c -s ./src/output.c -o ./build/output.o 



preprocessor:
	echo "reprocessor"

compiler:
	echo "compiler"

assembler:
	echo "assembler"

linker:
	echo "linker"

locator:
	echo "locator"

loader:
	echo "loader"

install:
	echo "install"

setup: 
	mkdir ./build

execute:
	./build/output

clean:
	rm -rf ./build/*.o

